(Source native)
(Cfg_str project_name luv-cli)
(Cfg_str project_slug luv-cli)
(Cfg_str project_description"luv wrapped in a cli")
(Cfg_str syntax Reason)
(Cfg_str package_manager Esy)
(Cfg_str test_framework Rely)
(Cfg_str ci_cd Github)
(Cfg_str author_name"Alain Armand")
(Cfg_str github_username idkjs)